//! (file) projection backend — turns skills/commands into runtime surface files.
//!
//! Owns the AGY + Claude skill/file projection backends.

pub mod agy;
pub mod claude_skill;
pub mod codex_agent;
pub mod tool_map;

mod support;
#[cfg(test)]
mod tests;

// SkillsProjectionHealthCheck is the only cross-crate consumer surface (cli doctor);
// the rest are crate-internal helpers used by the update_* drivers below.
pub use support::SkillsProjectionHealthCheck;
use support::*;

use ccync_foundation::config::CcyncConfig;
use ccync_foundation::json_util::read_json_map;
use ccync_foundation::platform::atomic_swap;
use ccync_foundation::render::create_temp_render_dir;
use ccync_foundation::runtime::{default_primary_runtime, VALID_RUNTIMES};
use codex_agent::parse_agent_meta;
use serde_json::Value;
use std::ffi::OsStr;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use thiserror::Error;

pub(crate) const CCYNC_MANAGED_FILE_HEADER: &str =
    "# Generated by CCYNC Setup-Machine. Do not edit manually.";

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ProjectionWarning {
    pub message: String,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ProjectionReport {
    pub written_files: Vec<PathBuf>,
    pub removed_paths: Vec<PathBuf>,
    pub created_links: Vec<PathBuf>,
    pub warnings: Vec<ProjectionWarning>,
}

/// A single skill/agent source directory registered for projection.
///
/// `id` uniquely identifies the source (e.g. `"ccync"`, `"my-bundle"`).
/// `persistent` marks sources whose projected artifacts must not be pruned
/// when the source is temporarily absent from the active invocation set.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectionSource {
    pub root: PathBuf,
    pub id: String,
    pub persistent: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkillUpdateOptions {
    pub repo_root: PathBuf,
    /// Ordered source list; ccync-core must always be first (baseline).
    /// Single-source callers pass a 1-element `Vec`.
    pub sources: Vec<ProjectionSource>,
    pub user_home: PathBuf,
    pub selected_runtimes: Vec<String>,
    pub dry_run: bool,
    pub replace: bool,
}

pub type CommandUpdateOptions = SkillUpdateOptions;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PersonalizationUpdateOptions {
    pub repo_root: PathBuf,
    pub source_root: PathBuf,
    pub user_home: PathBuf,
    pub appdata_root: PathBuf,
    pub selected_runtimes: Vec<String>,
    pub dry_run: bool,
    pub replace: bool,
    pub uninstall: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MachineUpdateOptions {
    pub repo_root: PathBuf,
    pub source_root: PathBuf,
    pub user_home: PathBuf,
    pub appdata_root: PathBuf,
    pub selected_runtimes: Vec<String>,
    pub primary_runtime: String,
    pub dry_run: bool,
    pub replace: bool,
    pub uninstall: bool,
    pub include_source_projections: bool,
}

#[derive(Debug, Error)]
pub enum AdapterError {
    #[error("{0}")]
    Message(String),
    #[error("{0}")]
    Io(#[from] io::Error),
}

pub fn machine_options_from_config(
    config: &CcyncConfig,
    dry_run: bool,
) -> Result<MachineUpdateOptions, AdapterError> {
    let (repo_root, source_root) = resolve_runtime_roots(config)?;
    let user_home = user_home()?;
    let appdata_root = appdata_root(&user_home);
    let selected_runtimes = load_selected_runtimes(&user_home)?;
    let primary_runtime = load_primary_runtime(&selected_runtimes, &user_home)?;
    Ok(MachineUpdateOptions {
        repo_root,
        source_root,
        user_home,
        appdata_root,
        selected_runtimes,
        primary_runtime,
        dry_run,
        replace: false,
        uninstall: false,
        // D-07: single mode — source projections always run from the canonical
        // root (no Dev-only gate). The managed-set source swap lands in a later task.
        include_source_projections: true,
    })
}

/// Assemble the ordered projection source list for a machine update or sync.
///
/// ccync-core (the canonical plugin root) is always first and persistent.
/// Additional installed sources (bundles, personal layer) are appended
/// when registered — reserved for extension in the bundle-installation layer.
pub fn collect_projection_sources(source_root: &Path) -> Vec<ProjectionSource> {
    vec![ProjectionSource {
        root: source_root.to_path_buf(),
        id: "ccync".to_string(),
        persistent: true,
    }]
}

/// The decomposed components of a single managed plugin directory: the skill and
/// command directory names, the agent file names (`*.agent.md`), and the MCP
/// server names declared in the plugin's `.mcp.json`.
///
/// This is the projection-input materialization — a managed plugin in the cache
/// is decomposed into the four component lists that feed `update_skills` /
/// `update_commands` and the MCP projection. All lists are name-sorted and
/// gracefully empty when the corresponding subtree / manifest is absent.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct PluginComponents {
    pub skills: Vec<String>,
    pub commands: Vec<String>,
    pub agents: Vec<String>,
    pub mcp_servers: Vec<String>,
}

/// Decompose a managed plugin directory into its component lists.
///
/// `skills` / `commands` are child directory names under `skills/` and
/// `commands/`; `agents` are the `*.agent.md` file names under `agents/`;
/// `mcp_servers` are the keys of the `servers` object in `<plugin>/.mcp.json`.
/// Missing subtrees or manifest degrade to empty lists (no error).
pub fn decompose_plugin(plugin_dir: &Path) -> Result<PluginComponents, AdapterError> {
    let skills = list_named_children(&plugin_dir.join("skills"))?;
    let commands = list_named_children(&plugin_dir.join("commands"))?;
    let agents = list_files_with_extension(&plugin_dir.join("agents"), "agent.md")?
        .into_iter()
        .filter_map(|p| p.file_name().and_then(OsStr::to_str).map(str::to_string))
        .collect();
    let mut mcp_servers: Vec<String> = Vec::new();
    if let Ok(content) = fs::read_to_string(plugin_dir.join(".mcp.json")) {
        if let Ok(v) = serde_json::from_str::<Value>(&content) {
            if let Some(servers) = v.get("servers").and_then(Value::as_object) {
                mcp_servers = servers.keys().cloned().collect();
            }
        }
    }
    mcp_servers.sort();
    Ok(PluginComponents {
        skills,
        commands,
        agents,
        mcp_servers,
    })
}

pub fn run_machine_update(opts: &MachineUpdateOptions) -> Result<ProjectionReport, AdapterError> {
    let mut report = run_update_personalization(&PersonalizationUpdateOptions {
        repo_root: opts.repo_root.clone(),
        source_root: opts.source_root.clone(),
        user_home: opts.user_home.clone(),
        appdata_root: opts.appdata_root.clone(),
        selected_runtimes: opts.selected_runtimes.clone(),
        dry_run: opts.dry_run,
        replace: opts.replace,
        uninstall: opts.uninstall,
    })?;

    if opts.include_source_projections {
        let sources = collect_projection_sources(&opts.source_root);
        extend_report(
            &mut report,
            run_update_skills(&SkillUpdateOptions {
                repo_root: opts.repo_root.clone(),
                sources: sources.clone(),
                user_home: opts.user_home.clone(),
                selected_runtimes: opts.selected_runtimes.clone(),
                dry_run: opts.dry_run,
                replace: opts.replace,
            })?,
        );
        extend_report(
            &mut report,
            run_update_commands(&CommandUpdateOptions {
                repo_root: opts.repo_root.clone(),
                sources,
                user_home: opts.user_home.clone(),
                selected_runtimes: opts.selected_runtimes.clone(),
                dry_run: opts.dry_run,
                replace: opts.replace,
            })?,
        );
    }

    Ok(report)
}

fn extend_report(report: &mut ProjectionReport, mut next: ProjectionReport) {
    report.written_files.append(&mut next.written_files);
    report.removed_paths.append(&mut next.removed_paths);
    report.created_links.append(&mut next.created_links);
    report.warnings.append(&mut next.warnings);
}

/// Resolve the projection roots. D-07: single mode — `repo_root` and
/// `source_root` are both the ccync canonical plugin root (`~/.ccync/plugins/ccync`),
/// which the canonical-root content render materializes. There is no Dev/Normal split and
/// no ccync-core lookup, so this never errors for "missing ccync-core" — only when the
/// home directory cannot be resolved.
fn resolve_runtime_roots(_config: &CcyncConfig) -> Result<(PathBuf, PathBuf), AdapterError> {
    let canonical = ccync_foundation::paths::canonical_plugin_root()
        .ok_or_else(|| AdapterError::Message("could not resolve canonical plugin root".into()))?;
    Ok((canonical.clone(), canonical))
}

fn user_home() -> Result<PathBuf, AdapterError> {
    #[cfg(windows)]
    {
        std::env::var_os("USERPROFILE")
            .map(PathBuf::from)
            .ok_or_else(|| AdapterError::Message("USERPROFILE is not set".into()))
    }
    #[cfg(not(windows))]
    {
        std::env::var_os("HOME")
            .map(PathBuf::from)
            .ok_or_else(|| AdapterError::Message("HOME is not set".into()))
    }
}

fn appdata_root(user_home: &Path) -> PathBuf {
    #[cfg(windows)]
    {
        std::env::var_os("APPDATA")
            .map(PathBuf::from)
            .unwrap_or_else(|| user_home.join("AppData").join("Roaming"))
    }
    #[cfg(not(windows))]
    {
        user_home.join(".config")
    }
}

fn load_selected_runtimes(user_home: &Path) -> Result<Vec<String>, AdapterError> {
    let install_state = user_home.join(".ccync").join("install-state.json");
    let raw = read_json_map(&install_state)?;
    let mut selected = raw
        .get("selectedRuntimes")
        .and_then(Value::as_array)
        .map(|values| {
            values
                .iter()
                .filter_map(Value::as_str)
                .map(|value| value.trim().to_ascii_lowercase())
                .filter(|value| VALID_RUNTIMES.contains(&value.as_str()))
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();
    if selected.is_empty() {
        selected = VALID_RUNTIMES
            .iter()
            .map(|value| (*value).to_string())
            .collect();
    }
    selected.sort();
    selected.dedup();
    Ok(selected)
}

fn load_primary_runtime(
    selected_runtimes: &[String],
    user_home: &Path,
) -> Result<String, AdapterError> {
    let install_state = user_home.join(".ccync").join("install-state.json");
    let raw = read_json_map(&install_state)?;
    if let Some(primary) = raw.get("primaryRuntime").and_then(Value::as_str) {
        let normalized = primary.trim().to_ascii_lowercase();
        if selected_runtimes.iter().any(|value| value == &normalized) {
            return Ok(normalized);
        }
    }
    let refs = selected_runtimes
        .iter()
        .map(String::as_str)
        .collect::<Vec<_>>();
    default_primary_runtime(&refs)
        .map(str::to_string)
        .ok_or_else(|| AdapterError::Message("could not resolve primary runtime".into()))
}

#[derive(Debug, Clone)]
struct SkillContext {
    opts: SkillUpdateOptions,
}

impl SkillContext {
    fn new(opts: SkillUpdateOptions) -> Self {
        Self { opts }
    }

    fn primary_source_root(&self) -> &Path {
        &self.opts.sources[0].root
    }

    fn copilot_root(&self) -> PathBuf {
        self.opts.user_home.join(".copilot")
    }

    fn gemini_root(&self) -> PathBuf {
        self.opts.user_home.join(".gemini")
    }

    fn codex_root(&self) -> PathBuf {
        self.opts.user_home.join(".codex")
    }

    fn codex_agents_target(&self) -> PathBuf {
        self.codex_root().join("agents")
    }

    fn antigravity_root(&self) -> PathBuf {
        self.gemini_root().join("antigravity-cli")
    }

    fn ccync_home(&self) -> PathBuf {
        self.opts.user_home.join(".ccync")
    }

    fn lockfile_path(&self) -> PathBuf {
        self.ccync_home().join("state").join("plugins.lock.json")
    }

    fn ccync_source_root(&self) -> PathBuf {
        self.ccync_home().join("source")
    }

    fn canonical_plugin_root(&self) -> PathBuf {
        self.ccync_home().join("plugins").join("ccync")
    }

    fn canonical_commands_root(&self) -> PathBuf {
        self.canonical_plugin_root().join("commands")
    }

    fn agents_target(&self) -> PathBuf {
        self.copilot_root().join("agents")
    }

    fn copilot_skills_target(&self) -> PathBuf {
        self.copilot_root().join("skills")
    }

    fn codex_skills_target(&self) -> PathBuf {
        self.codex_root().join("skills")
    }

    fn gemini_commands_target(&self) -> PathBuf {
        self.gemini_root().join("commands")
    }

    fn gemini_skills_target(&self) -> PathBuf {
        self.gemini_root().join("skills")
    }

    fn claude_commands_target(&self) -> PathBuf {
        self.opts.user_home.join(".claude").join("commands")
    }

    fn workspace_skills_target(&self) -> PathBuf {
        self.opts.repo_root.join(".agents").join("skills")
    }

    fn shared_skills_target(&self) -> PathBuf {
        self.opts.user_home.join(".agents").join("skills")
    }

    fn opencode_root(&self) -> PathBuf {
        self.opts.user_home.join(".config").join("opencode")
    }

    fn opencode_commands_target(&self) -> PathBuf {
        self.opencode_root().join("commands")
    }

    fn has_runtime(&self, runtime: &str) -> bool {
        self.opts.selected_runtimes.iter().any(|rt| rt == runtime)
    }
}

#[derive(Debug, Clone)]
struct PersonalizationContext {
    opts: PersonalizationUpdateOptions,
}

impl PersonalizationContext {
    fn new(opts: PersonalizationUpdateOptions) -> Self {
        Self { opts }
    }

    fn ccync_home(&self) -> PathBuf {
        self.opts.user_home.join(".ccync")
    }

    fn gemini_root(&self) -> PathBuf {
        self.opts.user_home.join(".gemini")
    }

    fn gemini_context_file(&self) -> PathBuf {
        self.gemini_root().join("ccync-context.md")
    }

    fn gemini_settings_file(&self) -> PathBuf {
        self.gemini_root().join("settings.json")
    }

    fn antigravity_root(&self) -> PathBuf {
        self.gemini_root().join("antigravity-cli")
    }

    fn workspace_agents_root(&self) -> PathBuf {
        self.opts.repo_root.join(".agents")
    }

    fn workspace_skills_target(&self) -> PathBuf {
        self.workspace_agents_root().join("skills")
    }

    fn workspace_rules_target(&self) -> PathBuf {
        self.workspace_agents_root().join("rules")
    }

    fn vscode_settings_file(&self) -> PathBuf {
        self.opts
            .appdata_root
            .join("Code")
            .join("User")
            .join("settings.json")
    }

    fn has_runtime(&self, runtime: &str) -> bool {
        self.opts
            .selected_runtimes
            .iter()
            .any(|value| value == runtime)
    }
}

pub fn run_update_skills(opts: &SkillUpdateOptions) -> Result<ProjectionReport, AdapterError> {
    let ctx = SkillContext::new(opts.clone());
    let mut report = ProjectionReport::default();
    update_skills(&ctx, &mut report)?;
    Ok(report)
}

pub fn run_update_commands(opts: &CommandUpdateOptions) -> Result<ProjectionReport, AdapterError> {
    let ctx = SkillContext::new(opts.clone());
    let mut report = ProjectionReport::default();
    update_commands(&ctx, &mut report)?;
    Ok(report)
}

pub fn run_update_personalization(
    opts: &PersonalizationUpdateOptions,
) -> Result<ProjectionReport, AdapterError> {
    let ctx = PersonalizationContext::new(opts.clone());
    let mut report = ProjectionReport::default();
    update_personalization(&ctx, &mut report)?;
    Ok(report)
}

fn update_skills(ctx: &SkillContext, report: &mut ProjectionReport) -> Result<(), AdapterError> {
    use std::collections::BTreeMap;

    // Collect skills and agents from all sources in order (ccync-core first = baseline).
    // Single-source (1-element Vec) degrades to the same result as before — byte-identical.
    // Collision warnings are added in the next implementation step.
    let mut skill_names: Vec<String> = Vec::new();
    let mut skill_source_id: BTreeMap<String, String> = BTreeMap::new();
    let mut agent_paths: Vec<PathBuf> = Vec::new();
    let mut agent_fname_source_id: BTreeMap<String, String> = BTreeMap::new();

    for src in &ctx.opts.sources {
        for name in list_named_children(&src.root.join("skills"))? {
            if let Some(owner) = skill_source_id.get(&name) {
                // Collision: core-wins + additive-only. Non-core sources may only add
                // new names; a clash with any prior source is skipped with a warning.
                report.warnings.push(ProjectionWarning {
                    message: format!(
                        "skill '{}' from source '{}' skipped: name already claimed by source '{}'",
                        name, src.id, owner
                    ),
                });
                continue;
            }
            skill_names.push(name.clone());
            skill_source_id.insert(name, src.id.clone());
        }
        for path in list_files_with_extension(&src.root.join("agents"), "agent.md")? {
            let fname = path
                .file_name()
                .and_then(OsStr::to_str)
                .unwrap_or("")
                .to_string();
            if let Some(owner) = agent_fname_source_id.get(&fname) {
                // Collision: core-wins + additive-only. Non-core sources may only add
                // new agent files; a clash with any prior source is skipped with a warning.
                report.warnings.push(ProjectionWarning {
                    message: format!(
                        "agent '{}' from source '{}' skipped: name already claimed by source '{}'",
                        fname, src.id, owner
                    ),
                });
                continue;
            }
            agent_paths.push(path);
            agent_fname_source_id.insert(fname, src.id.clone());
        }
    }

    let mut registry = ManagedArtifactRegistry::load(&ctx.lockfile_path(), report);
    registry.replace_category(MANAGED_AGENT_PATHS);
    registry.replace_category(MANAGED_CODEX_AGENT_PATHS);
    registry.replace_category(MANAGED_DISCUSS_SKILL_PATHS);
    registry.replace_category(MANAGED_LEGACY_PATHS);
    registry.replace_category(MANAGED_SKILL_PATHS);

    let shared_skills = ctx.opts.user_home.join(".agents").join("skills");
    let should_project_shared_skills = ctx
        .opts
        .selected_runtimes
        .iter()
        .any(|rt| rt == "codex" || rt == "opencode");
    if should_project_shared_skills {
        ensure_dir(&shared_skills, ctx.opts.dry_run)?;
        for skill_name in &skill_names {
            let source_id = skill_source_id
                .get(skill_name)
                .map(String::as_str)
                .unwrap_or("ccync");
            let source_root = ctx
                .opts
                .sources
                .iter()
                .find(|s| s.id == source_id)
                .map(|s| s.root.as_path())
                .unwrap_or_else(|| ctx.primary_source_root());
            let source = source_root.join("skills").join(skill_name);
            let link = shared_skills.join(skill_name);
            ensure_dir_link(&source, &link, ctx.opts.replace, ctx.opts.dry_run, report)?;
            registry.mark_with_source(MANAGED_SKILL_PATHS, &link, source_id);
        }
        let installed_ids: Vec<&str> = ctx.opts.sources.iter().map(|s| s.id.as_str()).collect();
        prune_stale_links(
            &shared_skills,
            skill_names.iter().map(String::as_str),
            ctx.opts.dry_run,
            report,
            &registry,
            &installed_ids,
        )?;
    } else {
        let installed_ids: Vec<&str> = ctx.opts.sources.iter().map(|s| s.id.as_str()).collect();
        prune_stale_links(
            &shared_skills,
            std::iter::empty(),
            ctx.opts.dry_run,
            report,
            &registry,
            &installed_ids,
        )?;
    }

    if ctx.opts.selected_runtimes.iter().any(|rt| rt == "copilot") {
        let ccync_root = ctx.copilot_root().join("ccync");
        ensure_dir(&ctx.ccync_home(), ctx.opts.dry_run)?;
        ensure_dir_link(
            &ctx.ccync_home(),
            &ccync_root,
            ctx.opts.replace,
            ctx.opts.dry_run,
            report,
        )?;
    }
    let should_keep_source_link = ctx
        .opts
        .selected_runtimes
        .iter()
        .any(|rt| rt == "gemini-cli" || rt.starts_with("agy-"));
    if should_keep_source_link {
        ensure_dir(&ctx.ccync_home(), ctx.opts.dry_run)?;
        ensure_dir_link(
            &ctx.opts.repo_root,
            &ctx.ccync_source_root(),
            ctx.opts.replace,
            ctx.opts.dry_run,
            report,
        )?;
    }
    if ctx
        .opts
        .selected_runtimes
        .iter()
        .any(|rt| rt == "gemini-cli")
    {
        let ccync_root = ctx.gemini_root().join("ccync");
        ensure_dir_link(
            &ctx.ccync_source_root(),
            &ccync_root,
            ctx.opts.replace,
            ctx.opts.dry_run,
            report,
        )?;
    }
    if ctx
        .opts
        .selected_runtimes
        .iter()
        .any(|rt| rt.starts_with("agy-"))
    {
        let ccync_root = ctx.antigravity_root().join("ccync");
        ensure_dir_link(
            &ctx.ccync_source_root(),
            &ccync_root,
            ctx.opts.replace,
            ctx.opts.dry_run,
            report,
        )?;
    }

    // --- Antigravity GUI (agy-gui) native projection ---
    // The GUI reads loose decomposed skills from ~/.gemini/antigravity/skills/ and
    // MCP servers from ~/.gemini/antigravity/mcp_config.json — NOT a whole-plugin
    // junction (that is the agy-cli / agy-ide face above). Per-skill links are
    // registry-tracked + pruned like the shared-skills surface.
    {
        let agy_gui_skills = agy::agy_gui_skills_root(&ctx.opts.user_home);
        let agy_gui_mcp = agy::agy_gui_mcp_config_path(&ctx.opts.user_home);
        let installed_ids: Vec<&str> = ctx.opts.sources.iter().map(|s| s.id.as_str()).collect();
        if ctx.has_runtime("agy-gui") {
            ensure_dir(&agy_gui_skills, ctx.opts.dry_run)?;
            for skill_name in &skill_names {
                let source_id = skill_source_id
                    .get(skill_name)
                    .map(String::as_str)
                    .unwrap_or("ccync");
                let source_root = ctx
                    .opts
                    .sources
                    .iter()
                    .find(|s| s.id == source_id)
                    .map(|s| s.root.as_path())
                    .unwrap_or_else(|| ctx.primary_source_root());
                let source = source_root.join("skills").join(skill_name);
                let link = agy_gui_skills.join(skill_name);
                ensure_dir_link(&source, &link, ctx.opts.replace, ctx.opts.dry_run, report)?;
                registry.mark_with_source(MANAGED_SKILL_PATHS, &link, source_id);
            }
            prune_stale_links(
                &agy_gui_skills,
                skill_names.iter().map(String::as_str),
                ctx.opts.dry_run,
                report,
                &registry,
                &installed_ids,
            )?;

            // MCP: mirror the canonical `.mcp.json` servers into the GUI config.
            let canonical_mcp = ctx.canonical_plugin_root().join(".mcp.json");
            let servers = fs::read_to_string(&canonical_mcp)
                .ok()
                .and_then(|c| serde_json::from_str::<Value>(&c).ok())
                .and_then(|v| v.get("servers").and_then(Value::as_object).cloned());
            if let Some(servers) = servers {
                if let Some(body) = agy::render_agy_gui_mcp_config(&servers) {
                    if write_text(&agy_gui_mcp, &body, ctx.opts.dry_run)? {
                        report.written_files.push(agy_gui_mcp.clone());
                    }
                }
            }
        } else {
            // agy-gui not selected: drop any CCYNC-owned GUI skill links + MCP config.
            prune_stale_links(
                &agy_gui_skills,
                std::iter::empty(),
                ctx.opts.dry_run,
                report,
                &registry,
                &installed_ids,
            )?;
            remove_file_if_present(&agy_gui_mcp, ctx.opts.dry_run, report)?;
        }
    }

    let agents_target = ctx.agents_target();
    ensure_dir(&agents_target, ctx.opts.dry_run)?;
    for agent_path in &agent_paths {
        let fname = agent_path
            .file_name()
            .and_then(OsStr::to_str)
            .ok_or_else(|| AdapterError::Message("invalid agent file name".into()))?;
        let target = agents_target.join(fname);
        // Generic projection: copy the plugin agent verbatim. The agent's own
        // frontmatter carries its Claude tool grants — there is no abstract-token
        // rewrite and no golem-roster filtering.
        let raw = fs::read_to_string(agent_path)?;
        write_text(&target, &raw, ctx.opts.dry_run)?;
        let source_id = agent_fname_source_id
            .get(fname)
            .map(String::as_str)
            .unwrap_or("ccync");
        registry.mark_with_source(MANAGED_AGENT_PATHS, &target, source_id);
    }
    let installed_ids: Vec<&str> = ctx.opts.sources.iter().map(|s| s.id.as_str()).collect();
    prune_stale_links(
        &agents_target,
        agent_paths
            .iter()
            .filter_map(|path| path.file_name().and_then(OsStr::to_str)),
        ctx.opts.dry_run,
        report,
        &registry,
        &installed_ids,
    )?;

    // --- Codex TOML subagent projection ---
    // Project each plugin agent to `~/.codex/agents/<name>.toml` (Codex's native
    // subagent format — a raw `.md` would not load). `model`/`reasoning_effort`
    // come from the agent's own frontmatter (generic — no golem-role routing);
    // an absent model omits the TOML model line. Sandbox defaults to read-only
    // (the safe default for an isolated subagent).
    if ctx.has_runtime("codex") {
        let codex_agents = ctx.codex_agents_target();
        ensure_dir(&codex_agents, ctx.opts.dry_run)?;

        let mut codex_toml_names: Vec<String> = Vec::new();
        for agent_path in &agent_paths {
            let raw = fs::read_to_string(agent_path)?;
            if let Some(meta) = parse_agent_meta(&raw) {
                let toml = codex_agent::serialize_codex_toml(
                    &meta,
                    meta.model.as_deref().unwrap_or(""),
                    meta.reasoning_effort.as_deref(),
                    tool_map::invocation_mode_to_codex_sandbox(tool_map::InvocationMode::Consult),
                );
                let toml_fname = format!("{}.toml", meta.name);
                let target = codex_agents.join(&toml_fname);
                write_text(&target, &toml, ctx.opts.dry_run)?;
                let fname_key = agent_path.file_name().and_then(OsStr::to_str).unwrap_or("");
                let source_id = agent_fname_source_id
                    .get(fname_key)
                    .map(String::as_str)
                    .unwrap_or("ccync");
                registry.mark_with_source(MANAGED_CODEX_AGENT_PATHS, &target, source_id);
                codex_toml_names.push(toml_fname);
            }
        }
        prune_stale_links(
            &codex_agents,
            codex_toml_names.iter().map(String::as_str),
            ctx.opts.dry_run,
            report,
            &registry,
            &installed_ids,
        )?;
    }

    if !ctx.opts.selected_runtimes.iter().any(|rt| rt == "opencode") {
        registry.persist(ctx.opts.dry_run, report)?;
        return Ok(());
    }

    let opencode_agents = ctx.opencode_root().join("agents");
    let staged_agents = if ctx.opts.dry_run {
        None
    } else {
        let parent = opencode_agents
            .parent()
            .ok_or_else(|| AdapterError::Message("OpenCode agent root has no parent".into()))?;
        Some(create_temp_render_dir(parent)?)
    };
    let opencode_target_root = staged_agents
        .as_deref()
        .unwrap_or(opencode_agents.as_path());
    ensure_dir(opencode_target_root, ctx.opts.dry_run)?;
    for agent_path in &agent_paths {
        let raw = fs::read_to_string(agent_path)?;
        let frontmatter = parse_frontmatter(&raw);
        let name = agent_path
            .file_stem()
            .and_then(OsStr::to_str)
            .unwrap_or("agent")
            .trim_end_matches(".agent");
        let target = opencode_target_root.join(format!("{name}.md"));
        let content = render_opencode_agent(name, &frontmatter, &strip_frontmatter(&raw));
        write_text(&target, &content, ctx.opts.dry_run)?;
    }
    if let Some(staged_agents) = staged_agents {
        atomic_swap(&staged_agents, &opencode_agents)
            .map_err(|e| AdapterError::Message(format!("OpenCode agent swap failed: {e}")))?;
        report.written_files.push(opencode_agents.clone());
    }

    let legacy_paths = [
        ctx.copilot_root().join("skills"),
        ctx.gemini_root().join("skills"),
        ctx.codex_root().join("skills"),
        ctx.antigravity_root().join("skills"),
    ];
    for path in legacy_paths {
        remove_if_ccync_owned_dir(&path, ctx.opts.dry_run, report, &registry)?;
    }

    registry.persist(ctx.opts.dry_run, report)?;
    Ok(())
}

fn update_commands(ctx: &SkillContext, report: &mut ProjectionReport) -> Result<(), AdapterError> {
    let commands_root = ctx.primary_source_root().join("commands");
    let canonical_commands_root = ctx.canonical_commands_root();
    let command_dirs = list_command_dirs(&commands_root)?;
    if command_dirs.is_empty() {
        return Ok(());
    }
    let mut registry = ManagedArtifactRegistry::load(&ctx.lockfile_path(), report);
    registry.replace_category(MANAGED_COMMAND_PATHS);

    ensure_dir(&canonical_commands_root, ctx.opts.dry_run)?;
    ensure_dir(&ctx.gemini_commands_target(), ctx.opts.dry_run)?;
    ensure_dir(&ctx.opencode_commands_target(), ctx.opts.dry_run)?;

    let active_names = command_dirs
        .iter()
        .filter_map(|dir| dir.file_name().and_then(OsStr::to_str))
        .collect::<Vec<_>>();

    for command_dir in &command_dirs {
        let name = command_dir
            .file_name()
            .and_then(OsStr::to_str)
            .ok_or_else(|| AdapterError::Message("invalid command directory name".into()))?;
        let canonical_command_dir = canonical_commands_root.join(name);
        ensure_dir(&canonical_command_dir, ctx.opts.dry_run)?;

        let template_path = command_dir.join("SKILL.template.md");
        let rendered_source = bake_command_content(command_dir, &ctx.opts.repo_root)?;
        let baked_skill = canonical_command_dir.join("SKILL.md");
        if write_text(&baked_skill, &rendered_source, ctx.opts.dry_run)? {
            report.written_files.push(baked_skill.clone());
        }
        registry.mark(MANAGED_COMMAND_PATHS, &baked_skill);

        if template_path.is_file() {
            let stale_worktree_bake = command_dir.join("SKILL.md");
            if stale_worktree_bake.is_file() {
                if !ctx.opts.dry_run {
                    fs::remove_file(&stale_worktree_bake)?;
                }
                report.removed_paths.push(stale_worktree_bake);
            }
        }

        // Copilot has no slash-command concept; expose each command as a skill
        // (`~/.copilot/skills/<name>/SKILL.md`, triggered `/ccync-status`). When
        // copilot is not selected, clean any command-skill CCYNC wrote before.
        if ctx.opts.selected_runtimes.iter().any(|rt| rt == "copilot") {
            if let Some(skill_file) = write_command_skill(
                &ctx.copilot_skills_target(),
                name,
                &rendered_source,
                ctx.opts.dry_run,
                report,
                &registry,
            )? {
                registry.mark(MANAGED_COMMAND_PATHS, &skill_file);
            }
        } else {
            remove_ccync_command_skill(
                &ctx.copilot_skills_target(),
                name,
                &ctx.opts.repo_root,
                &registry,
                ctx.opts.dry_run,
                report,
            )?;
        }

        // Codex's capability unit is a skill at the shared ~/.agents/skills
        // (official path), invoked $ccync-status. Always drop the legacy wrong-target
        // ~/.codex/skills link. Gate the shared command-skill on codex being
        // selected so an opencode-only install (opencode also reads ~/.agents/skills
        // but has its own native command projection) does not get a command-skill
        // on top of its native command — the double-load guard.
        remove_link_if_present(
            &ctx.codex_skills_target().join(name),
            ctx.opts.dry_run,
            report,
        )?;

        if ctx.opts.selected_runtimes.iter().any(|rt| rt == "codex") {
            if let Some(skill_file) = write_command_skill(
                &ctx.shared_skills_target(),
                name,
                &rendered_source,
                ctx.opts.dry_run,
                report,
                &registry,
            )? {
                registry.mark(MANAGED_COMMAND_PATHS, &skill_file);
            }
        } else {
            // codex not selected: clean any CCYNC-written command-skill so it does
            // not linger in the shared dir (read by opencode/copilot) and cause a
            // double-load; user dirs and unrelated links are left untouched.
            remove_ccync_command_skill(
                &ctx.shared_skills_target(),
                name,
                &ctx.opts.repo_root,
                &registry,
                ctx.opts.dry_run,
                report,
            )?;
        }

        remove_link_if_present(
            &ctx.antigravity_root().join("skills").join(name),
            ctx.opts.dry_run,
            report,
        )?;
        remove_link_if_present(
            &ctx.workspace_skills_target().join(name),
            ctx.opts.dry_run,
            report,
        )?;
        let frontmatter = parse_frontmatter(&rendered_source);
        let body = strip_frontmatter(&rendered_source);

        let gemini_target = ctx.gemini_commands_target().join(format!("{name}.toml"));
        if ctx
            .opts
            .selected_runtimes
            .iter()
            .any(|rt| rt == "gemini-cli")
        {
            if write_text(
                &gemini_target,
                &render_gemini_command(name, &frontmatter, &body),
                ctx.opts.dry_run,
            )? {
                report.written_files.push(gemini_target.clone());
            }
            registry.mark(MANAGED_COMMAND_PATHS, &gemini_target);
        } else {
            remove_managed_file_if_present(&gemini_target, ctx.opts.dry_run, report, &registry)?;
        }

        let claude_target = ctx.claude_commands_target().join(format!("{name}.md"));
        remove_managed_file_if_present(&claude_target, ctx.opts.dry_run, report, &registry)?;

        let opencode_target = ctx.opencode_commands_target().join(format!("{name}.md"));
        if ctx.opts.selected_runtimes.iter().any(|rt| rt == "opencode") {
            if write_text(
                &opencode_target,
                &render_opencode_command(name, &frontmatter, &body),
                ctx.opts.dry_run,
            )? {
                report.written_files.push(opencode_target.clone());
            }
            registry.mark(MANAGED_COMMAND_PATHS, &opencode_target);
        } else {
            remove_managed_file_if_present(&opencode_target, ctx.opts.dry_run, report, &registry)?;
        }
    }

    let link_cleanup_roots = [
        ctx.copilot_skills_target(),
        ctx.gemini_skills_target(),
        ctx.antigravity_root().join("skills"),
        ctx.shared_skills_target(),
        ctx.codex_skills_target(),
    ];
    for root in link_cleanup_roots {
        prune_stale_command_links(&root, &active_names, ctx.opts.dry_run, report, &registry)?;
        prune_legacy_ccync_prefixed_dirs(
            &root,
            &active_names,
            ctx.opts.dry_run,
            report,
            &registry,
        )?;
    }
    prune_stale_managed_files(
        &ctx.gemini_commands_target(),
        "toml",
        &active_names,
        ctx.opts.dry_run,
        report,
        &registry,
    )?;
    prune_stale_managed_files(
        &ctx.claude_commands_target(),
        "md",
        &active_names,
        ctx.opts.dry_run,
        report,
        &registry,
    )?;
    prune_stale_managed_files(
        &ctx.opencode_commands_target(),
        "md",
        &active_names,
        ctx.opts.dry_run,
        report,
        &registry,
    )?;

    registry.persist(ctx.opts.dry_run, report)?;
    Ok(())
}

fn update_personalization(
    ctx: &PersonalizationContext,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    let skill_names = list_named_children(&ctx.opts.source_root.join("skills"))?;

    ensure_dir(&ctx.ccync_home(), ctx.opts.dry_run)?;
    ensure_dir(&ctx.gemini_root(), ctx.opts.dry_run)?;
    ensure_dir(&ctx.antigravity_root(), ctx.opts.dry_run)?;

    let gemini_context = ctx.gemini_context_file();
    if ctx.opts.uninstall || !ctx.has_runtime("gemini-cli") {
        remove_file_if_present(&gemini_context, ctx.opts.dry_run, report)?;
    } else {
        let context_content = skill_names
            .iter()
            .map(|name| {
                format!(
                    "@{}",
                    ctx.opts
                        .source_root
                        .join("skills")
                        .join(name)
                        .join("SKILL.md")
                        .display()
                )
            })
            .collect::<Vec<_>>()
            .join("\n");
        write_text_with_report(&gemini_context, &context_content, ctx.opts.dry_run, report)?;
    }

    if !ctx.opts.uninstall && ctx.has_runtime("gemini-cli") {
        if let Some(mut settings) = read_json_map_or_warn(&ctx.gemini_settings_file(), report)? {
            merge_context_file_names(&mut settings, &["AGENTS.md", "GEMINI.md"]);
            write_json_map_with_report(
                &ctx.gemini_settings_file(),
                &settings,
                ctx.opts.dry_run,
                report,
            )?;
        }
    }

    // D-07/D-08: AGY projection is owned solely by install.rs `AgyProjection`
    // (rebuilt by the agy-cli/agy-ide/agy-gui split). The former personalization
    // AGY build here was gated by a Dev-mode predicate that is permanently off
    // after the single-mode collapse, so it was dead + a duplicate of install.rs
    // and is removed.

    let workspace_rule_file = ctx.workspace_rules_target().join("ccync.md");
    if workspace_rule_file.exists() {
        if !is_ccync_managed_file(&workspace_rule_file) {
            report.warnings.push(ProjectionWarning {
                message: format!(
                    "preserved user-owned repo rule: {}",
                    workspace_rule_file.display()
                ),
            });
        } else {
            remove_file_if_present(&workspace_rule_file, ctx.opts.dry_run, report)?;
        }
    }
    for dir in [
        ctx.workspace_skills_target(),
        ctx.workspace_rules_target(),
        ctx.workspace_agents_root(),
    ] {
        remove_empty_dir_if_present(&dir, ctx.opts.dry_run, report)?;
    }

    if !ctx.opts.uninstall && ctx.has_runtime("copilot") {
        if let Some(mut settings) = read_json_map_or_warn(&ctx.vscode_settings_file(), report)? {
            set_vscode_skills_bridge(&mut settings);
            write_json_map_with_report(
                &ctx.vscode_settings_file(),
                &settings,
                ctx.opts.dry_run,
                report,
            )?;
        }
    }

    // D-08: the dead source-repo workflow tail (the routing-template copy, the
    // source-repo git config-filter + hooks-path registration, and the local-env
    // re-checkout) is removed — ccync has no clean/smudge subcommands and no
    // source-repo git-filter workflow.
    Ok(())
}
